name: Lonely Runner Lean certificate

on:
  push:
    branches: ["lonely-runner-lean4"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          build: true
          test: false
          lint: false
          use-mathlib-cache: true
          leanchecker: true
